---

name: Build and Push Docker Image

on:
  # Allows you to run workflow manually from Actions tab
  workflow_dispatch:
#     inputs:
#       tags:
#         description: 'Docker Tag'
#         required: true
#         default: 'latest'
  push:
    branches: [main,master]
    tags:
      - 'v*.*.*'
    # Only build when files in these directories have been changed
    paths:
      - client/**
      - server/**
      - index.js
      - package.json

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Release version
        id: release_version
        run: |
          app_version=$(grep version package.json | sed -e 's/\s*"version":\s"\(.*\)",/\1/g')
          echo "app_version=$app_version" >> $GITHUB_ENV

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/audiobookshelf:latest
            ${{ secrets.DOCKER_USERNAME }}/audiobookshelf:${{ env.app_version }}
